// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackTraceMoney.Infrastructure.Persistence;

#nullable disable

namespace TrackTraceMoney.Infrastructure.Migrations
{
    [DbContext(typeof(TrackTraceMoneyDbContext))]
    [Migration("20260910072449_AddLoanPayment")]
    partial class AddLoanPayment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("TrackTraceMoney.Domain.Accounts.FinancialAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("Accounts", (string)null);

                    b.HasDiscriminator<string>("AccountType").HasValue("FinancialAccount");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TrackTraceMoney.Domain.Budgets.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "Year", "Month", "Currency")
                        .IsUnique();

                    b.ToTable("Budgets", (string)null);
                });

            modelBuilder.Entity("TrackTraceMoney.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SystemKey");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("TrackTraceMoney.Domain.CreditAccounts.CreditAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AmountOwed")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreditAccountType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("CreditAccounts", (string)null);

                    b.HasDiscriminator<string>("CreditAccountType").HasValue("CreditAccount");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TrackTraceMoney.Domain.CreditAccounts.CreditCardStatement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreditAccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("CycleEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("CycleStartDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinimumPayment")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PayInFullAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreditAccountId", "CycleEndDate")
                        .IsUnique();

                    b.ToTable("CreditCardStatements", (string)null);
                });

            modelBuilder.Entity("TrackTraceMoney.Domain.People.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomRelationshipLabel")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("People", (string)null);
                });

            modelBuilder.Entity("TrackTraceMoney.Domain.RecurringExpenses.RecurringExpense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("LastConfirmedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("RecurringExpenses", (string)null);
                });

            modelBuilder.Entity("TrackTraceMoney.Domain.Transactions.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.ToTable("Transactions", (string)null);

                    b.HasDiscriminator<string>("TransactionType").HasValue("Transaction");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TrackTraceMoney.Domain.Accounts.BankAccount", b =>
                {
                    b.HasBaseType("TrackTraceMoney.Domain.Accounts.FinancialAccount");

                    b.Property<string>("AccountNumberLast4")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("BankName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Bank");
                });

            modelBuilder.Entity("TrackTraceMoney.Domain.Accounts.CashAccount", b =>
                {
                    b.HasBaseType("TrackTraceMoney.Domain.Accounts.FinancialAccount");

                    b.HasDiscriminator().HasValue("Cash");
                });

            modelBuilder.Entity("TrackTraceMoney.Domain.Accounts.SavingsAccount", b =>
                {
                    b.HasBaseType("TrackTraceMoney.Domain.Accounts.FinancialAccount");

                    b.Property<decimal?>("GoalAmount")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Savings");
                });

            modelBuilder.Entity("TrackTraceMoney.Domain.CreditAccounts.CreditCard", b =>
                {
                    b.HasBaseType("TrackTraceMoney.Domain.CreditAccounts.CreditAccount");

                    b.Property<decimal?>("AnnualInterestRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("TEXT");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastFourDigits")
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MonthlyInterestRate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentDueDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatementCutOffDay")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("CreditCard");
                });

            modelBuilder.Entity("TrackTraceMoney.Domain.CreditAccounts.Loan", b =>
                {
                    b.HasBaseType("TrackTraceMoney.Domain.CreditAccounts.CreditAccount");

                    b.Property<decimal?>("Fees")
                        .HasColumnType("TEXT");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonthlyInstallment")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("NextPaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OriginalAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("RateType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RequiredPayment")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Loan");
                });

            modelBuilder.Entity("TrackTraceMoney.Domain.Transactions.CreditCardPayment", b =>
                {
                    b.HasBaseType("TrackTraceMoney.Domain.Transactions.Transaction");

                    b.Property<Guid>("CreditAccountId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("CreditAccountId");

                    b.Property<Guid>("SourceAccountId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("SourceAccountId");

                    b.HasIndex("CreditAccountId");

                    b.HasIndex("SourceAccountId");

                    b.HasDiscriminator().HasValue("CreditCardPayment");
                });

            modelBuilder.Entity("TrackTraceMoney.Domain.Transactions.CreditCardPurchase", b =>
                {
                    b.HasBaseType("TrackTraceMoney.Domain.Transactions.Transaction");

                    b.Property<Guid?>("BeneficiaryPersonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("CategoryId");

                    b.Property<Guid>("CreditAccountId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("CreditAccountId");

                    b.Property<Guid?>("PayerPersonId")
                        .HasColumnType("TEXT");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreditAccountId");

                    b.ToTable("Transactions", t =>
                        {
                            t.Property("BeneficiaryPersonId")
                                .HasColumnName("CreditCardPurchase_BeneficiaryPersonId");

                            t.Property("PayerPersonId")
                                .HasColumnName("CreditCardPurchase_PayerPersonId");
                        });

                    b.HasDiscriminator().HasValue("CreditCardPurchase");
                });

            modelBuilder.Entity("TrackTraceMoney.Domain.Transactions.Expense", b =>
                {
                    b.HasBaseType("TrackTraceMoney.Domain.Transactions.Transaction");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BeneficiaryPersonId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("CategoryId");

                    b.Property<Guid?>("PayerPersonId")
                        .HasColumnType("TEXT");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.HasDiscriminator().HasValue("Expense");
                });

            modelBuilder.Entity("TrackTraceMoney.Domain.Transactions.Income", b =>
                {
                    b.HasBaseType("TrackTraceMoney.Domain.Transactions.Transaction");

                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("CategoryId");

                    b.Property<Guid>("DestinationAccountId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("DestinationAccountId");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("TEXT");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DestinationAccountId");

                    b.HasDiscriminator().HasValue("Income");
                });

            modelBuilder.Entity("TrackTraceMoney.Domain.Transactions.LoanPayment", b =>
                {
                    b.HasBaseType("TrackTraceMoney.Domain.Transactions.Transaction");

                    b.Property<Guid>("CreditAccountId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("CreditAccountId");

                    b.Property<Guid>("SourceAccountId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("SourceAccountId");

                    b.HasIndex("CreditAccountId");

                    b.HasIndex("SourceAccountId");

                    b.HasDiscriminator().HasValue("LoanPayment");
                });

            modelBuilder.Entity("TrackTraceMoney.Domain.Transactions.Transfer", b =>
                {
                    b.HasBaseType("TrackTraceMoney.Domain.Transactions.Transaction");

                    b.Property<Guid>("DestinationAccountId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("DestinationAccountId");

                    b.Property<Guid>("SourceAccountId")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("TEXT")
                        .HasColumnName("SourceAccountId");

                    b.HasIndex("DestinationAccountId");

                    b.HasIndex("SourceAccountId");

                    b.HasDiscriminator().HasValue("Transfer");
                });
#pragma warning restore 612, 618
        }
    }
}
